# Generated by Django 3.1.6 on 2021-02-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('diagnostic', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('question_1', models.CharField(max_length=30)),
                ('question_2', models.CharField(max_length=30)),
                ('question_3', models.CharField(max_length=30)),
                ('question_4', models.CharField(max_length=30)),
                ('question_5', models.CharField(max_length=30)),
                ('question_6', models.CharField(max_length=30)),
            ],
        ),
    ]
