# Generated by Django 3.1.6 on 2021-02-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=70)),
                ('is_supplementary', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('programme_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('programme_name', models.CharField(max_length=70)),
            ],
        ),
    ]
